### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by tendai-zw** [Raikia/UhOh365#7] opened 2019-12-09 10:08 UTC
I is returning valid for non-existent emails. Is the API endpoint still functional?

**Comment by darcosion** [comment] 2019-12-20 16:05
I've read some part of the code and I think it's related with that : 

https://github.com/Raikia/UhOh365/blob/4a46c75a4c1bb84f5f12caede8c4f0257bfb6180/UhOh365.py#L65

Where they are a response with ```200``` http code and without 365 domain, it's considered like true.
But, on this issue #9 it seem than a redirect to another API could be required.

Please, give some example or screenshot to confirm that.

**Comment by Raikia** [comment] 2020-02-26 23:31
Duplicate of #9.  As I said there:

If you give an example email set, I can test what you mean. If you'd like to privately share, send to raikiasec@gmail.com. Its hard to debug something like this generically because o365 has some absurd and irregular API responses

**Closed as completed by Raikia** 2020-02-26 23:31 UTC
Labels: duplicate
